services:
  nginx:
    container_name: dojo-manager-nginx
    image: dojo-manager/nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
    volumes:
      - ./:/var/www/vhost/:cached
      - ./docker/nginx/certs:/etc/nginx/ssl
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/vhost/
    ports:
      - '80:80'
      - '443:443'
    networks:
      - dojo-manager-network

  php:
    container_name: dojo-manager-php
    image: dojo-manager/php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      PHP_MEMORY_LIMIT: '128M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    ports:
      - '9000:9000'
    networks:
      - dojo-manager-network

  mysql:
    container_name: dojo-manager-sql
    image: mysql/mysql-server:latest
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dojo_manager'
      MYSQL_USER: 'dojo_manager'
      MYSQL_PASSWORD: 'dojo_manager_local'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'
    networks:
      - dojo-manager-network

networks:
  dojo-manager-network:
    driver: bridge
